# Required configs
k_folds: 40
probe_type: "svm"
probe_params: 
  C_start_end: [0.001, 1000]
  kernel_degree_list: [2, 3]
  kernel_gamma_start_end: [0.0001, 10]
  kernel_coef0_start_end: [-1, 2]
  opt_params:
    n_iter: 50
    n_jobs: 1
    n_points: 1
    optimizer_kwargs:
      base_estimator: "RF"
      n_initial_points: 5
    verbose: 1

# Optional configs
embedding_dim: null
standardize_embeddings: true
normalize_labels: true
enable_plots: false
update_leaderboard: false
store_probes: false
task_filter: null #eg. ["biomass_mean", "biomass_std"]